# Generated by Django 4.1.5 on 2023-01-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
